### ISSUE TITLE
Addition of Categories Cloud 

### ISSUE THREAD

**Issue by Akash-Sharma-1** [lynn9388/light-blog#2]
Can you please give some suggestions on how to add a functional Category Cloud in the side section?
![image](https://user-images.githubusercontent.com/33986563/88525882-d20bc280-d018-11ea-8605-33750ce5de60.png)

Thanks :)

**Comment by lynn9388** [comment]
@Akash-Sharma-1 I'll try to add that feature this weekend.

**Comment by lynn9388** [comment]
@Akash-Sharma-1 I referenced [this](https://github.com/mzlogin/mzlogin.github.io/blob/master/_includes/sidebar-categories-cloud.html) implementation and it was a lot easier than I thought it would be.
